version: "3.7"
services:
  api:
    build: ./
    container_name: notekeeper-api
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_DB_HOST: db
      MYSQL_DB_PORT: 3333
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: ""
      MYSQL_DB_DATABASE: notekeeper
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./src:/app/src
  db:
    build: ../notekeeper-db
    container_name: notekeeper-db
    ports:
      - 3333:3333
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      BITNAMI_DEBUG: "true"
      TZ: UTC
    volumes:
      - db:/bitnami/mariadb
  redis:
    image: redis:6.0.8
    ports:
      - 6379:6379

volumes:
  db:
